# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
